### PR TITLE
Initial Commit

### PR DESCRIPTION
**Pull request by Genaro-Chris**
Here are a few things I added
Formatting all the swift files
Support for Route.Result.bytes enum case
Support for task cancellation in RouteResponseProtocol.async method

### CODE REVIEW

**Comment by RandomHashTags** [comment]
There is a lot to unpack here in one commit. I see only a few additions/changes worth accepting.

Can you explain why you made these changes to help me understand how accepting them would benefit the project?

**Comment by Genaro-Chris** [comment]
Task cancellation support is required because read or write operation would stop if the task running it is cancelled. 
Ability to use the Route.Result.bytes enum case see main.swift file
Formatting because it was looking a bit messy

**Comment by RandomHashTags** [comment]
So here are my takeaways:
### Benefits the project
- organizing imports
- read/write buffer if not cancelled
- escaping route responses when applicable
- adding missing `bytes` implementation for `Route.Result`

### Hurt the project
- adding (sometimes inconsistent) whitespace (even just a single space) to declarations, expression variables, and initialization parameters
  - this is syntax noise and makes it harder to read and keep context in scope
  - how does adding this whitespace benefit readability?
- making route responses async when they shouldn't be
  - current implementation only supports blocking or async responses, not both
- removing `public` from an extension declaration, even though all children in the extension should be publicly available, and adding it to every child declaration
  - this is more syntax noise and hurts readability (also a waste of bytes on disk)

Mainly comes down to syntax preferences. One should try to use a library's original formatting unless there are real-world reasons why not to.

You can create smaller separate PRs with similar changes (one for organizing imports, another for adding checked cancelled read/write buffer, a third for adding `bytes` implementation for `Route.Result`, etc) and I will do my best to accept them. I cannot accept this PR in its current state.

**Comment by Genaro-Chris** [comment]
Okay

**Pull request closed without merging**
